//! # nexus-dag-dsl
//!
//! A type-safe Rust domain-specific language for constructing Nexus DAGs
//! programmatically. The DSL emits the canonical [`nexus_sdk::types::Dag`]
//! wire struct, which can be serialized to the JSON form consumed by every
//! Nexus tool (CLI `dag validate` / `dag publish` / `dag execute`).
//!
//! Two authoring variants coexist in a single crate:
//!
//! - **Relaxed** ([`DagBuilder`]) — string-keyed ports, validation at
//!   [`DagBuilder::build`]. Works with any tool, no descriptors required.
//! - **Strict** ([`TypedDagBuilder`]) — typed port handles via
//!   [`ToolDescriptor`], port-payload type mismatches are compile errors.
//!   Descriptors can be hand-written, generated by the `nexus-toolkit`
//!   derive macro, or emitted by `nexus-dsl-codegen` — all three paths
//!   produce interchangeable descriptor code.
//!
//! Two authoring surfaces coexist in each variant:
//!
//! - **Flat** — 1:1 mirror of the JSON wire format; every edge-kind has a
//!   dedicated method.
//! - **Scoped** — lexical loop bodies via closures; for-each / collect and
//!   do-while / break pairs are enforced by scope construction.
//!
//! The crate re-exports the wire types from [`nexus_sdk::types`] for
//! convenience so that users need not depend on `nexus-sdk` directly.

#![warn(missing_docs)]

// Public re-exports from the SDK so callers don't need to depend on
// `nexus-sdk` directly for the wire types they build against.
pub use nexus_sdk::{
    types::{
        Dag,
        DefaultValue,
        Edge,
        EdgeKind,
        EntryGroup,
        EntryPort,
        FromPort,
        ToPort,
        Vertex,
        VertexKind,
        DEFAULT_ENTRY_GROUP,
    },
    ToolFqn,
};

// TODO: module wiring lands here as each work item completes:
//   - `mod builder;`    — flat relaxed DagBuilder
//   - `mod typed;`      — flat strict TypedDagBuilder + ToolDescriptor
//   - `mod scoped;`     — scoped for_each / do_while layer
//   - `mod error;`      — DagError type
//   - `pub use ...;`    — public re-exports once each module lands
