[package]
name = "nexus-rust-toolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
schemars = "0.8.21"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
warp = "0.3.7"

[dev-dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
