[package]
name = "nexus-toolkit"
description = "Rust framework for building and serving Nexus Tools."
documentation = "https://docs.rs/nexus-toolkit"
publish = ["crates-io"]

edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
bytes = "1"
ed25519-dalek = "2"
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
hex.workspace = true
hyper-util = { version = "0.1", features = ["server-auto", "http1", "http2", "service", "tokio"] }
warp.workspace = true
env_logger.workspace = true
log.workspace = true
notify = "8.2.0"
tls-listener.workspace = true
tokio = { version = "1", features = ["sync", "time", "rt-multi-thread", "macros"] }
tokio-rustls.workspace = true
tokio-stream.workspace = true
tracing = "0.1"
# === Nexus deps ===
nexus-sdk = { workspace = true, features = ["signed_http", "types"] }

[dev-dependencies]
http-body-util = "0.1"
rcgen = "0.13"
reqwest = { version = "0.12.14", default-features = false, features = ["json", "rustls-tls"] }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs"] }
tempfile.workspace = true
tokio = { version = "1.44.1", features = ["macros"] }
