//! SDK accessors for generated scheduler model types.

use crate::{
    move_bindings::{
        interface::agent as agent_move,
        scheduler::{
            schedule::{Occurrence, OccurrenceSource},
            task::{Task, TaskController, TaskStatus},
        },
    },
    sui,
};

impl agent_move::ExecutionSelection {
    pub fn dag_id(&self) -> Option<sui::types::Address> {
        match self {
            Self::AgentSkill { selected_dag, .. } => {
                selected_dag.as_option().map(|dag_id| dag_id.bytes)
            }
            Self::DefaultAgent { dag_id } => Some(dag_id.bytes),
        }
    }

    pub fn agent_id(&self) -> Option<sui::types::Address> {
        match self {
            Self::AgentSkill { agent_id, .. } => Some(agent_id.bytes),
            Self::DefaultAgent { .. } => None,
        }
    }

    pub fn is_default_agent(&self) -> bool {
        matches!(self, Self::DefaultAgent { .. })
    }

    pub fn is_agent_skill(&self) -> bool {
        matches!(self, Self::AgentSkill { .. })
    }
}

impl agent_move::AgentExecutionConfig {
    pub fn network_address(&self) -> sui::types::Address {
        self.network.bytes
    }

    pub fn entry_group_name(&self) -> &str {
        self.entry_group.as_str()
    }
}

impl Occurrence {
    pub fn deadline(&self) -> Option<u64> {
        self.deadline_ms.copied_option()
    }

    pub fn is_manual(&self) -> bool {
        matches!(self.source, OccurrenceSource::Manual)
    }
}

impl OccurrenceSource {
    /// Returns whether the occurrence was scheduled explicitly.
    pub fn is_manual(&self) -> bool {
        matches!(self, Self::Manual)
    }

    /// Returns whether the occurrence was generated by a recurrence.
    pub fn is_recurring(&self) -> bool {
        matches!(self, Self::Recurring { .. })
    }
}

impl Task {
    pub fn object_id(&self) -> sui::types::Address {
        self.id.id.bytes
    }

    pub fn advertised_occurrence(&self) -> Option<&Occurrence> {
        let occurrence_id = self.schedule.advertised_occurrence_id.copied_option()?;
        self.schedule
            .pending
            .iter()
            .chain(
                self.schedule
                    .recurrence
                    .as_option()
                    .map(|recurrence| &recurrence.next),
            )
            .find(|occurrence| occurrence.id == occurrence_id)
    }

    pub fn controller_agent_id(&self) -> Option<sui::types::Address> {
        match &self.controller {
            TaskController::Agent { pos0 } => Some(pos0.bytes),
            TaskController::Address { .. } => None,
        }
    }

    pub fn is_active(&self) -> bool {
        matches!(self.status, TaskStatus::Active)
    }
}
