//! SDK accessors for generated scheduler model types.

use crate::{
    move_bindings::{
        interface::agent::{self as agent_move, SkillSchedulePolicy},
        scheduler::{
            schedule::{Occurrence, OccurrenceSource, Schedule},
            task::{Task, TaskController, TaskStatus},
        },
    },
    sui,
};

impl agent_move::ExecutionSelection {
    pub fn dag_id(&self) -> Option<sui::types::Address> {
        match self {
            Self::AgentSkill { selected_dag, .. } => {
                selected_dag.as_option().map(|dag_id| dag_id.bytes)
            }
            Self::DefaultAgent { dag_id } => Some(dag_id.bytes),
        }
    }

    pub fn agent_id(&self) -> Option<sui::types::Address> {
        match self {
            Self::AgentSkill { agent_id, .. } => Some(agent_id.bytes),
            Self::DefaultAgent { .. } => None,
        }
    }

    pub fn is_default_agent(&self) -> bool {
        matches!(self, Self::DefaultAgent { .. })
    }

    pub fn is_agent_skill(&self) -> bool {
        matches!(self, Self::AgentSkill { .. })
    }
}

impl agent_move::AgentExecutionConfig {
    pub fn network_address(&self) -> sui::types::Address {
        self.network.bytes
    }

    pub fn entry_group_name(&self) -> &str {
        self.entry_group.as_str()
    }
}

impl Occurrence {
    pub fn deadline(&self) -> Option<u64> {
        self.deadline_ms.copied_option()
    }

    pub fn is_standalone(&self) -> bool {
        matches!(self.source, OccurrenceSource::Standalone)
    }
}

impl OccurrenceSource {
    /// Returns whether the occurrence is independent of a recurrence.
    pub fn is_standalone(&self) -> bool {
        matches!(self, Self::Standalone)
    }

    /// Returns whether the occurrence was generated by a recurrence.
    pub fn is_recurring(&self) -> bool {
        matches!(self, Self::Recurring { .. })
    }
}

impl Schedule {
    /// Returns the effective start time for an [`Occurrence`] under the given [`SkillSchedulePolicy`].
    pub fn effective_start_time_ms(
        &self,
        policy: &SkillSchedulePolicy,
        occurrence: &Occurrence,
    ) -> u64 {
        let min_interval_ms = match policy {
            SkillSchedulePolicy::Once => 0,
            SkillSchedulePolicy::Recurring {
                min_interval_ms, ..
            } => *min_interval_ms,
        };
        let earliest = self
            .last_dispatch_ms
            .copied_option()
            .map_or(0, |last_dispatch_ms| {
                last_dispatch_ms.saturating_add(min_interval_ms)
            });
        occurrence.start_time_ms.max(earliest)
    }
}

impl Task {
    pub fn object_id(&self) -> sui::types::Address {
        self.id.id.bytes
    }

    pub fn advertised_occurrence(&self) -> Option<&Occurrence> {
        let occurrence_id = self.schedule.advertised_occurrence_id.copied_option()?;
        self.scheduled_occurrence(occurrence_id)
    }

    /// Returns one occurrence that remains in the current schedule.
    pub fn scheduled_occurrence(&self, occurrence_id: u64) -> Option<&Occurrence> {
        self.schedule
            .pending
            .iter()
            .chain(
                self.schedule
                    .recurrence
                    .as_option()
                    .map(|recurrence| &recurrence.next),
            )
            .find(|occurrence| occurrence.id == occurrence_id)
    }

    pub fn controller_agent_id(&self) -> Option<sui::types::Address> {
        match &self.controller {
            TaskController::Agent { pos0 } => Some(pos0.bytes),
            TaskController::Address { .. } => None,
        }
    }

    pub fn is_active(&self) -> bool {
        matches!(self.status, TaskStatus::Active)
    }

    /// Returns whether the Task has released its live resources.
    pub fn is_finalized(&self) -> bool {
        matches!(self.status, TaskStatus::Finalized)
    }
}

#[cfg(test)]
mod tests {
    use {super::*, crate::move_bindings::move_std::option::Option as MoveOption};

    #[test]
    fn effective_start_respects_the_last_dispatch_interval() {
        let schedule = Schedule::new(
            vec![],
            MoveOption::from_option(None),
            MoveOption::from_option(None),
            1,
            1,
            MoveOption::from_option(Some(100)),
        );
        let occurrence = Occurrence::new(
            1,
            105,
            MoveOption::from_option(None),
            10,
            OccurrenceSource::Standalone,
        );
        let policy = SkillSchedulePolicy::Recurring {
            min_interval_ms: 20,
            max_occurrences: MoveOption::from_option(None),
        };

        assert_eq!(schedule.effective_start_time_ms(&policy, &occurrence), 120);
    }
}
