//! Build script for `nexus-sdk`.
//!
//! Two responsibilities:
//! 1. Expose the pinned Sui SDK tag as a compile-time env var.
//! 2. Render address-free Move identifier constants from the committed IR in
//!    `src/idents/generated/ir/*.json` into one `$OUT_DIR/idents_<package>.rs`
//!    per package, each `include!`d by the matching `crate::idents` submodule.
//!    Rendering is fully offline — the network half (refreshing the IR JSON)
//!    lives in the `generate_binding` binary (see `just sdk rebind`).

use {
    std::{collections::BTreeMap, fs, path::Path},
    sui_move_codegen::{
        ir::{NormalizedModule, NormalizedPackage},
        render::{render_package, RenderOptions},
    },
};

fn main() {
    emit_sui_sdk_tag();
    render_generated_bindings();
}

fn emit_sui_sdk_tag() {
    let cargo_toml = fs::read_to_string("Cargo.toml").expect("Should find Cargo.toml");
    let parsed: toml::Value = cargo_toml.parse().expect("Cargo.toml should valid");

    let sui_sdk_tag = &parsed["dependencies"]["sui_package_management"]["tag"]
        .as_str()
        .expect("Should read dependencies.sui_package_management tag");

    println!("cargo:rustc-env=SUI_SDK_TAG={sui_sdk_tag}");
}

/// Reads every `src/idents/generated/ir/<package>.json` and renders one
/// `$OUT_DIR/idents_<package>.rs` file of `ModuleAndNameIdent` constants. Each
/// Move module becomes a unit struct whose associated consts name its functions
/// and datatypes; the matching `crate::idents` submodule `include!`s the file
/// alongside its hand-written helpers. Package addresses present in the IR are
/// intentionally discarded: the SDK supplies the package id at call time from
/// `NexusObjects`, so the generated constants stay address-free and reusable
/// across deployments.
fn render_generated_bindings() {
    let ir_dir = Path::new("src/idents/generated/ir");
    println!("cargo:rerun-if-changed={}", ir_dir.display());

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");

    if !ir_dir.is_dir() {
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(ir_dir)
        .expect("Failed to read IR directory")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "json"))
        .collect();
    entries.sort();

    let packages = load_ir_packages(&entries);

    for (package, path, json, normalized) in packages.values() {
        println!("cargo:rerun-if-changed={}", path.display());

        let mut out =
            String::from("// @generated by build.rs from src/idents/generated/ir — do not edit.\n");
        out.push_str(&render_idents_package(json, &path.display().to_string()));

        let out_path = Path::new(&out_dir).join(format!("idents_{package}.rs"));
        fs::write(&out_path, out)
            .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_path.display()));

        if should_render_types_package(package) {
            let normalized = filter_types_package(package, normalized);
            let type_out = render_types_package(&normalized, package, &packages);
            let type_out = strip_root_reexports(&type_out);
            write_types_package_files(package, &type_out, Path::new(&out_dir));
        }
    }
}

fn should_render_types_package(package: &str) -> bool {
    matches!(
        package,
        "interface" | "primitives" | "registry" | "scheduler" | "sui_framework" | "workflow"
    )
}

fn load_ir_packages(
    entries: &[std::path::PathBuf],
) -> BTreeMap<String, (String, std::path::PathBuf, String, NormalizedPackage)> {
    entries
        .iter()
        .map(|path| {
            let package = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("IR file must have a UTF-8 stem")
                .to_string();
            let json = fs::read_to_string(path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));
            let normalized = NormalizedPackage::from_json_str(&json)
                .unwrap_or_else(|e| panic!("Failed to parse IR JSON {}: {e}", path.display()));

            (package.clone(), (package, path.clone(), json, normalized))
        })
        .collect()
}

/// Renders the module bodies for a single package's IR JSON.
fn render_idents_package(json: &str, source: &str) -> String {
    let value: serde_json::Value = serde_json::from_str(json)
        .unwrap_or_else(|e| panic!("Failed to parse IR JSON {source}: {e}"));
    let modules = value
        .get("modules")
        .and_then(serde_json::Value::as_object)
        .unwrap_or_else(|| panic!("IR JSON {source} missing `modules` object"));

    let mut out = String::new();
    // `modules` comes from a BTreeMap, so iteration is already name-sorted.
    for (module_name, module) in modules {
        let struct_name = to_pascal_case(module_name);

        let mut consts = String::new();
        let mut used: Vec<String> = Vec::new();

        // Functions first, then datatypes; datatype consts that would collide
        // with a function const get a `_TYPE` suffix (Move keeps functions and
        // types in separate namespaces, so a clash is legal on-chain).
        for func in array_of(module, "functions") {
            if let Some(name) = item_name(func) {
                let const_name = unique(&mut used, to_screaming_snake_case(name), "");
                consts.push_str(&render_const(&const_name, module_name, name));
            }
        }
        for datatype in array_of(module, "datatypes") {
            if let Some(name) = item_name(datatype) {
                let const_name = unique(&mut used, to_screaming_snake_case(name), "_TYPE");
                consts.push_str(&render_const(&const_name, module_name, name));
            }
        }

        out.push_str(&format!(
            "    /// Identifiers in the `{module_name}` module.\n    pub struct {struct_name};\n\n    impl {struct_name} {{\n{consts}    }}\n\n"
        ));
    }
    out
}

fn render_types_package(
    normalized: &NormalizedPackage,
    package: &str,
    packages: &BTreeMap<String, (String, std::path::PathBuf, String, NormalizedPackage)>,
) -> String {
    let mut opts = RenderOptions {
        emit_types: true,
        emit_calls: false,
        emit_tx_ext: false,
        flatten: false,
        use_aliases: true,
        external_types: BTreeMap::new(),
    };

    for (external_package, (_, _, _, external)) in packages {
        if external_package == package {
            continue;
        }
        if !should_render_types_package(external_package) {
            continue;
        }
        opts.add_external_package(
            &filter_types_package(external_package, external),
            format!("crate::types::generated::{external_package}_types"),
        );
    }

    add_move_std_compat_external_types(&mut opts);

    adapt_rendered_types(package, render_package(normalized, &opts))
}

fn adapt_rendered_types(package: &str, code: String) -> String {
    match package {
        "interface" => code
            .replace(
                "phantoms = \"T0\",\n    )]\n    pub struct AnnounceVerifierPackageEvent",
                "phantoms = \"T0\",\n        type_abilities = \"T0: copy, drop\",\n    )]\n    pub struct AnnounceVerifierPackageEvent",
            )
            .replace(
                "pub struct AgentVertexAuthorizationTemplate {\n        pub skill_id: u64,",
                "pub struct AgentVertexAuthorizationTemplate {\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_tap_u64_value\")]\n        pub skill_id: u64,",
            )
            .replace(
                "pub struct InterfaceVersion {\n        pub inner: u64,\n    }",
                "#[serde(from = \"crate::types::generated_support::InterfaceVersionSerde\", into = \"crate::types::generated_support::InterfaceVersionSerde\")]\n    pub struct InterfaceVersion {\n        pub inner: u64,\n    }",
            )
            .replace(
                "pub struct SkillRequirement {\n        pub input_commitment: Vec<u8>,",
                "pub struct SkillRequirement {\n        #[serde(alias = \"input_schema_commitment\")]\n        pub input_commitment: Vec<u8>,",
            )
            .replace(
                "pub struct RequestScheduledExecution<T0> {\n        pub request: T0,\n        pub priority: u64,\n        pub request_ms: u64,\n        pub start_ms: u64,\n        pub deadline_ms: u64,",
                "pub struct RequestScheduledExecution<T0> {\n        pub request: T0,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub priority: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub request_ms: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub start_ms: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub deadline_ms: u64,",
            )
            .replace(
                "pub mode: VerifierMode,",
                "#[serde(deserialize_with = \"crate::types::generated_support::deserialize_published_move_enum\")]\n        pub mode: VerifierMode,",
            )
            .replace(
                "pub decision: VerifierDecision,",
                "#[serde(deserialize_with = \"crate::types::generated_support::deserialize_published_move_enum\")]\n        pub decision: VerifierDecision,",
            )
            .replace(
                "pub submission_kind: VerificationSubmissionKind,",
                "#[serde(deserialize_with = \"crate::types::generated_support::deserialize_published_move_enum\")]\n        pub submission_kind: VerificationSubmissionKind,",
            )
            .replace(
                "pub failure_evidence_kind: FailureEvidenceKind,",
                "#[serde(deserialize_with = \"crate::types::generated_support::deserialize_published_move_enum\")]\n        pub failure_evidence_kind: FailureEvidenceKind,",
            ),
        "primitives" => code
            .replace(
                "        sm::__private::serde::Serialize,\n        sm::__private::serde::Deserialize,\n    )]\n    #[serde(crate = \"sui_move::__private::serde\")]\n    pub enum Symbol {",
                "    )]\n    pub enum Symbol {",
            )
            .replace(
                "pub struct TransitionConfigKey<T0, T1> {",
                "#[serde(bound(\n        serialize = \"T0: sm::__private::serde::Serialize, T1: sm::__private::serde::Serialize\",\n        deserialize = \"T0: sm::__private::serde::de::DeserializeOwned, T1: sm::__private::serde::Deserialize<'de>\"\n    ))]\n    pub struct TransitionConfigKey<T0, T1> {",
            )
            .replace(
                "pub struct TransitionKey<T0, T1> {",
                "#[serde(bound(\n        serialize = \"T0: sm::__private::serde::Serialize, T1: sm::__private::serde::Serialize\",\n        deserialize = \"T0: sm::__private::serde::de::DeserializeOwned, T1: sm::__private::serde::Deserialize<'de>\"\n    ))]\n    pub struct TransitionKey<T0, T1> {",
            )
            .replace(
                "pub struct NexusData {\n        pub storage: Vec<u8>,\n        pub one: Vec<u8>,\n        pub many: Vec<Vec<u8>>,",
                "pub struct NexusData {\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_tap_byte_vector\")]\n        pub storage: Vec<u8>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_tap_byte_vector\")]\n        pub one: Vec<u8>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_tap_byte_vector_vec\")]\n        pub many: Vec<Vec<u8>>,",
            ),
        "scheduler" => code
            .replace(
                "        sm::__private::serde::Serialize,\n        sm::__private::serde::Deserialize,\n    )]\n    #[serde(crate = \"sui_move::__private::serde\")]\n    pub enum State {",
                "        sm::__private::serde::Serialize,\n    )]\n    pub enum State {",
            )
            .replace(
                "pub struct Occurrence {\n        pub start_time_ms: u64,\n        pub deadline_ms: crate::types::MoveOption<u64>,\n        pub priority_fee_per_gas_unit: u64,",
                "pub struct Occurrence {\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub start_time_ms: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_move_option_sui_u64\")]\n        pub deadline_ms: crate::types::MoveOption<u64>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub priority_fee_per_gas_unit: u64,",
            )
            .replace(
                "pub struct PeriodicGeneratorState {\n        pub active: crate::types::MoveOption<Occurrence>,\n        pub next_start_ms: crate::types::MoveOption<u64>,\n        pub period_ms: u64,\n        pub deadline_offset_ms: crate::types::MoveOption<u64>,\n        pub max_iterations: crate::types::MoveOption<u64>,\n        pub generated: u64,\n        pub last_emitted_start_ms: crate::types::MoveOption<u64>,\n        pub priority_fee_per_gas_unit: u64,",
                "pub struct PeriodicGeneratorState {\n        pub active: crate::types::MoveOption<Occurrence>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_move_option_sui_u64\")]\n        pub next_start_ms: crate::types::MoveOption<u64>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub period_ms: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_move_option_sui_u64\")]\n        pub deadline_offset_ms: crate::types::MoveOption<u64>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_move_option_sui_u64\")]\n        pub max_iterations: crate::types::MoveOption<u64>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub generated: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_move_option_sui_u64\")]\n        pub last_emitted_start_ms: crate::types::MoveOption<u64>,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub priority_fee_per_gas_unit: u64,",
            )
            .replace(
                "pub struct QueueEntry {\n        pub occurrence: Occurrence,\n        pub sequence: u64,\n        pub request_ms: u64,",
                "pub struct QueueEntry {\n        pub occurrence: Occurrence,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub sequence: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub request_ms: u64,",
            )
            .replace(
                "pub struct QueueGeneratorState {\n        pub pending: crate::types::generated::sui_framework_types::priority_queue::PriorityQueue<\n            QueueEntry,\n        >,\n        pub len: u64,\n        pub next_sequence: u64,",
                "pub struct QueueGeneratorState {\n        pub pending: crate::types::generated::sui_framework_types::priority_queue::PriorityQueue<\n            QueueEntry,\n        >,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub len: u64,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_sui_u64\", serialize_with = \"crate::types::serde_parsers::serialize_sui_u64\")]\n        pub next_sequence: u64,",
            ),
        "registry" => code.replace(
            "Leader,\n        >",
            "crate::types::generated_support::Ignored,\n        >",
        ),
        "sui_framework" => code
            .replace(
                "pub struct ID {\n        pub bytes: sm::prelude::Address,\n    }",
                "#[serde(from = \"crate::types::generated_support::ObjectIdSerde\", into = \"crate::types::generated_support::ObjectIdSerde\")]\n    pub struct ID {\n        pub bytes: sm::prelude::Address,\n    }",
            )
            .replace(
                "module = \"vec_map\",\n        abilities = \"store, copy, drop\",",
                "module = \"vec_map\",\n        abilities = \"store, drop\",",
            )
            .replace(
                "pub struct LinkedTable<T0, T1> {",
                "#[serde(bound(\n        serialize = \"T0: sm::__private::serde::Serialize\",\n        deserialize = \"T0: sm::__private::serde::de::DeserializeOwned\"\n    ))]\n    pub struct LinkedTable<T0, T1> {",
            )
            .replace(
                "pub struct Node<T0, T1> {",
                "#[serde(bound(\n        serialize = \"T0: sm::__private::serde::Serialize, T1: sm::__private::serde::Serialize\",\n        deserialize = \"T0: sm::__private::serde::de::DeserializeOwned, T1: sm::__private::serde::de::DeserializeOwned\"\n    ))]\n    pub struct Node<T0, T1> {",
            ),
        "workflow" => code
            .replace(
            "pub struct RequestWalkExecutionEvent {\n        pub dag: crate::types::generated::sui_framework_types::object::ID,\n        pub execution: crate::types::generated::sui_framework_types::object::ID,\n        pub invoker: sm::prelude::Address,\n        pub walk_index: u64,\n        pub next_vertex: crate::types::generated::interface_types::graph::RuntimeVertex,\n        pub evaluations: crate::types::generated::sui_framework_types::object::ID,\n        pub agent_id: crate::types::generated::sui_framework_types::object::ID,\n        pub skill_id: u64,",
            "pub struct RequestWalkExecutionEvent {\n        pub dag: crate::types::generated::sui_framework_types::object::ID,\n        pub execution: crate::types::generated::sui_framework_types::object::ID,\n        pub invoker: sm::prelude::Address,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_tap_u64_value\")]\n        pub walk_index: u64,\n        pub next_vertex: crate::types::generated::interface_types::graph::RuntimeVertex,\n        pub evaluations: crate::types::generated::sui_framework_types::object::ID,\n        pub agent_id: crate::types::generated::sui_framework_types::object::ID,\n        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_tap_u64_value\")]\n        pub skill_id: u64,",
            )
            .replace(
                "        pub scheduled_occurrence_index: crate::types::MoveOption<u64>,",
                "        #[serde(deserialize_with = \"crate::types::serde_parsers::deserialize_move_option_sui_u64\")]\n        pub scheduled_occurrence_index: crate::types::MoveOption<u64>,",
            ),
        _ => code,
    }
}

fn add_move_std_compat_external_types(opts: &mut RenderOptions) {
    for type_name in ["0x1::ascii::String", "0x1::string::String"] {
        opts.add_external_type(
            sui_move_codegen::ir::TypeName::parse(type_name).expect("valid Move type"),
            "crate::types::generated_support::MoveString",
            false,
        );
    }

    for (type_name, rust_path, is_key) in [
        ("0x1::option::Option", "crate::types::MoveOption", false),
        ("0x1::type_name::TypeName", "crate::types::TypeName", false),
    ] {
        opts.add_external_type(
            sui_move_codegen::ir::TypeName::parse(type_name).expect("valid Move type"),
            rust_path,
            is_key,
        );
    }
}

fn filter_types_package(package: &str, normalized: &NormalizedPackage) -> NormalizedPackage {
    let modules = normalized
        .modules
        .iter()
        .filter_map(|(module_name, module)| {
            if !should_render_type_module(package, module_name) {
                return None;
            }

            let datatypes = module.datatypes.clone();
            if datatypes.is_empty() {
                return None;
            }
            Some((
                module_name.clone(),
                NormalizedModule {
                    name: module.name.clone(),
                    datatypes,
                    functions: Vec::new(),
                },
            ))
        })
        .collect();

    NormalizedPackage {
        storage_id: normalized.storage_id.clone(),
        original_id: normalized.original_id.clone(),
        version: normalized.version,
        modules,
    }
}

fn should_render_type_module(package: &str, module: &str) -> bool {
    if package != "sui_framework" {
        return true;
    }

    matches!(
        module,
        "bag"
            | "balance"
            | "linked_table"
            | "object"
            | "object_bag"
            | "object_table"
            | "priority_queue"
            | "sui"
            | "table"
            | "table_vec"
            | "url"
            | "vec_map"
            | "vec_set"
    )
}

fn strip_root_reexports(code: &str) -> String {
    code.lines()
        .filter(|line| !line.trim_start().starts_with("pub use "))
        .map(|line| {
            let mut line = line.to_string();
            line.push('\n');
            line
        })
        .collect()
}

fn write_types_package_files(package: &str, code: &str, out_dir: &Path) {
    let (root, modules) = split_rendered_type_modules(code);
    let mut package_out =
        String::from("// @generated by build.rs from src/idents/generated/ir — do not edit.\n");
    package_out.push_str(&root);

    for (module, body) in modules {
        let module_file = format!("{package}_{module}_types.rs");
        package_out.push_str(&format!(
            "include!(concat!(env!(\"OUT_DIR\"), \"/{module_file}\"));\n"
        ));

        let mut module_out =
            String::from("// @generated by build.rs from src/idents/generated/ir — do not edit.\n");
        module_out.push_str(&body);
        let out_path = out_dir.join(&module_file);
        fs::write(&out_path, module_out)
            .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_path.display()));
    }

    let out_path = out_dir.join(format!("{package}_types.rs"));
    fs::write(&out_path, package_out)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_path.display()));
}

fn split_rendered_type_modules(code: &str) -> (String, Vec<(String, String)>) {
    let mut root = String::new();
    let mut modules = Vec::new();
    let mut current: Option<(String, String)> = None;

    for line in code.lines() {
        if let Some(module) = rendered_module_name(line) {
            if let Some(module) = current.take() {
                modules.push(module);
            }
            let mut body = String::new();
            body.push_str(line);
            body.push('\n');
            current = Some((module.to_string(), body));
            continue;
        }

        match &mut current {
            Some((_, body)) => {
                body.push_str(line);
                body.push('\n');
            }
            None => {
                root.push_str(line);
                root.push('\n');
            }
        }
    }

    if let Some(module) = current {
        modules.push(module);
    }

    (root, modules)
}

fn rendered_module_name(line: &str) -> Option<&str> {
    line.strip_prefix("pub mod ")?.strip_suffix(" {")
}

fn render_const(const_name: &str, module: &str, name: &str) -> String {
    format!(
        "        /// Move identifier `{module}::{name}`.\n        pub const {const_name}: crate::idents::ModuleAndNameIdent = crate::idents::ModuleAndNameIdent {{\n            module: crate::sui::types::Identifier::from_static(\"{module}\"),\n            name: crate::sui::types::Identifier::from_static(\"{name}\"),\n        }};\n"
    )
}

fn array_of<'a>(module: &'a serde_json::Value, key: &str) -> &'a [serde_json::Value] {
    module
        .get(key)
        .and_then(serde_json::Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[])
}

fn item_name(item: &serde_json::Value) -> Option<&str> {
    item.get("name").and_then(serde_json::Value::as_str)
}

/// Returns `base` (optionally with `suffix`) ensuring uniqueness within `used`.
fn unique(used: &mut Vec<String>, base: String, suffix: &str) -> String {
    let mut candidate = if used.contains(&base) {
        format!("{base}{suffix}")
    } else {
        base
    };
    while used.contains(&candidate) {
        candidate.push_str("_X");
    }
    used.push(candidate.clone());
    candidate
}

/// `tool_registry` -> `ToolRegistry`.
fn to_pascal_case(input: &str) -> String {
    input
        .split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// `DAGExecution` -> `DAG_EXECUTION`, `output_port_from_string` ->
/// `OUTPUT_PORT_FROM_STRING`. Inserts `_` at lower→upper and
/// `<upper>(<upper><lower>)` boundaries, collapses existing underscores, then
/// uppercases.
fn to_screaming_snake_case(input: &str) -> String {
    let chars: Vec<char> = input.chars().collect();
    let mut out = String::new();
    for (i, &c) in chars.iter().enumerate() {
        if c == '_' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            continue;
        }
        if i > 0 && c.is_ascii_uppercase() {
            let prev = chars[i - 1];
            let next_is_lower = chars.get(i + 1).is_some_and(|n| n.is_ascii_lowercase());
            let boundary = prev.is_ascii_lowercase()
                || prev.is_ascii_digit()
                || (prev.is_ascii_uppercase() && next_is_lower);
            if boundary && !out.ends_with('_') {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}
