//! Build script for `nexus-sdk`.
//!
//! Two responsibilities:
//! 1. Expose the pinned Sui SDK tag as a compile-time env var.
//! 2. Render address-free Move identifier constants from the committed IR in
//!    `src/idents/generated/ir/*.json` into one `$OUT_DIR/idents_<package>.rs`
//!    per package, each `include!`d by the matching `crate::idents` submodule.
//!    Rendering is fully offline — the network half (refreshing the IR JSON)
//!    lives in the `generate_binding` binary (see `just regenerate-idents`).

use std::{fs, path::Path};

fn main() {
    emit_sui_sdk_tag();
    render_generated_idents();
}

fn emit_sui_sdk_tag() {
    let cargo_toml = fs::read_to_string("Cargo.toml").expect("Should find Cargo.toml");
    let parsed: toml::Value = cargo_toml.parse().expect("Cargo.toml should valid");

    let sui_sdk_tag = &parsed["dependencies"]["sui_package_management"]["tag"]
        .as_str()
        .expect("Should read dependencies.sui_package_management tag");

    println!("cargo:rustc-env=SUI_SDK_TAG={sui_sdk_tag}");
}

/// Reads every `src/idents/generated/ir/<package>.json` and renders one
/// `$OUT_DIR/idents_<package>.rs` file of `ModuleAndNameIdent` constants. Each
/// Move module becomes a unit struct whose associated consts name its functions
/// and datatypes; the matching `crate::idents` submodule `include!`s the file
/// alongside its hand-written helpers. Package addresses present in the IR are
/// intentionally discarded: the SDK supplies the package id at call time from
/// `NexusObjects`, so the generated constants stay address-free and reusable
/// across deployments.
fn render_generated_idents() {
    let ir_dir = Path::new("src/idents/generated/ir");
    println!("cargo:rerun-if-changed={}", ir_dir.display());

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");

    if !ir_dir.is_dir() {
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(ir_dir)
        .expect("Failed to read IR directory")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "json"))
        .collect();
    entries.sort();

    for path in entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let package = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("IR file must have a UTF-8 stem")
            .to_string();
        let json = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));

        let mut out =
            String::from("// @generated by build.rs from src/idents/generated/ir — do not edit.\n");
        out.push_str(&render_package(&json, &path.display().to_string()));

        let out_path = Path::new(&out_dir).join(format!("idents_{package}.rs"));
        fs::write(&out_path, out)
            .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_path.display()));
    }
}

/// Renders the module bodies for a single package's IR JSON.
fn render_package(json: &str, source: &str) -> String {
    let value: serde_json::Value = serde_json::from_str(json)
        .unwrap_or_else(|e| panic!("Failed to parse IR JSON {source}: {e}"));
    let modules = value
        .get("modules")
        .and_then(serde_json::Value::as_object)
        .unwrap_or_else(|| panic!("IR JSON {source} missing `modules` object"));

    let mut out = String::new();
    // `modules` comes from a BTreeMap, so iteration is already name-sorted.
    for (module_name, module) in modules {
        let struct_name = to_pascal_case(module_name);

        let mut consts = String::new();
        let mut used: Vec<String> = Vec::new();

        // Functions first, then datatypes; datatype consts that would collide
        // with a function const get a `_TYPE` suffix (Move keeps functions and
        // types in separate namespaces, so a clash is legal on-chain).
        for func in array_of(module, "functions") {
            if let Some(name) = item_name(func) {
                let const_name = unique(&mut used, to_screaming_snake_case(name), "");
                consts.push_str(&render_const(&const_name, module_name, name));
            }
        }
        for datatype in array_of(module, "datatypes") {
            if let Some(name) = item_name(datatype) {
                let const_name = unique(&mut used, to_screaming_snake_case(name), "_TYPE");
                consts.push_str(&render_const(&const_name, module_name, name));
            }
        }

        out.push_str(&format!(
            "    /// Identifiers in the `{module_name}` module.\n    pub struct {struct_name};\n\n    impl {struct_name} {{\n{consts}    }}\n\n"
        ));
    }
    out
}

fn render_const(const_name: &str, module: &str, name: &str) -> String {
    format!(
        "        /// Move identifier `{module}::{name}`.\n        pub const {const_name}: crate::idents::ModuleAndNameIdent = crate::idents::ModuleAndNameIdent {{\n            module: crate::sui::types::Identifier::from_static(\"{module}\"),\n            name: crate::sui::types::Identifier::from_static(\"{name}\"),\n        }};\n"
    )
}

fn array_of<'a>(module: &'a serde_json::Value, key: &str) -> &'a [serde_json::Value] {
    module
        .get(key)
        .and_then(serde_json::Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or(&[])
}

fn item_name(item: &serde_json::Value) -> Option<&str> {
    item.get("name").and_then(serde_json::Value::as_str)
}

/// Returns `base` (optionally with `suffix`) ensuring uniqueness within `used`.
fn unique(used: &mut Vec<String>, base: String, suffix: &str) -> String {
    let mut candidate = if used.contains(&base) {
        format!("{base}{suffix}")
    } else {
        base
    };
    while used.contains(&candidate) {
        candidate.push_str("_X");
    }
    used.push(candidate.clone());
    candidate
}

/// `tool_registry` -> `ToolRegistry`.
fn to_pascal_case(input: &str) -> String {
    input
        .split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// `DAGExecution` -> `DAG_EXECUTION`, `output_port_from_string` ->
/// `OUTPUT_PORT_FROM_STRING`. Inserts `_` at lower→upper and
/// `<upper>(<upper><lower>)` boundaries, collapses existing underscores, then
/// uppercases.
fn to_screaming_snake_case(input: &str) -> String {
    let chars: Vec<char> = input.chars().collect();
    let mut out = String::new();
    for (i, &c) in chars.iter().enumerate() {
        if c == '_' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            continue;
        }
        if i > 0 && c.is_ascii_uppercase() {
            let prev = chars[i - 1];
            let next_is_lower = chars.get(i + 1).is_some_and(|n| n.is_ascii_lowercase());
            let boundary = prev.is_ascii_lowercase()
                || prev.is_ascii_digit()
                || (prev.is_ascii_uppercase() && next_is_lower);
            if boundary && !out.ends_with('_') {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}
