//! Build script for `nexus-sdk`.
//!
//! Two responsibilities:
//! 1. Expose the pinned Sui SDK tag as a compile time env var.
//! 2. Render generated Move bindings from committed package IR in `src/move_bindings/ir/*.json`.

use {
    std::{collections::BTreeMap, fs, path::Path},
    sui_move_codegen::{
        ir::NormalizedPackage,
        render::{render_package_parts, RenderOptions},
    },
};

fn main() {
    emit_sui_sdk_tag();
    render_move_bindings();
}

fn emit_sui_sdk_tag() {
    let cargo_toml = fs::read_to_string("Cargo.toml").expect("Should find Cargo.toml");
    let parsed: toml::Value = cargo_toml.parse().expect("Cargo.toml should valid");

    let sui_sdk_tag = &parsed["dependencies"]["sui_package_management"]["tag"]
        .as_str()
        .expect("Should read dependencies.sui_package_management tag");

    println!("cargo:rustc-env=SUI_SDK_TAG={sui_sdk_tag}");
}

/// Reads every committed package IR file and renders the generated SDK Move boundary.
fn render_move_bindings() {
    let ir_dir = Path::new("src/move_bindings/ir");
    println!("cargo:rerun-if-changed={}", ir_dir.display());

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");

    if !ir_dir.is_dir() {
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(ir_dir)
        .expect("Failed to read IR directory")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "json"))
        .collect();
    entries.sort();

    let packages = load_ir_packages(&entries);

    for (package, path, normalized) in packages.values() {
        println!("cargo:rerun-if-changed={}", path.display());

        let generated = render_move_binding_package(normalized, package, &packages);
        write_move_binding_package_files(package, generated, Path::new(&out_dir));
    }
}

fn load_ir_packages(
    entries: &[std::path::PathBuf],
) -> BTreeMap<String, (String, std::path::PathBuf, NormalizedPackage)> {
    entries
        .iter()
        .map(|path| {
            let package = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("IR file must have a UTF-8 stem")
                .to_string();
            let contents = fs::read_to_string(path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));
            let normalized = NormalizedPackage::from_json_str(&contents)
                .unwrap_or_else(|e| panic!("Failed to parse IR JSON {}: {e}", path.display()));

            (package.clone(), (package, path.clone(), normalized))
        })
        .collect()
}

fn render_move_binding_package(
    normalized: &NormalizedPackage,
    package: &str,
    packages: &BTreeMap<String, (String, std::path::PathBuf, NormalizedPackage)>,
) -> sui_move_codegen::render::RenderedPackageParts {
    let mut opts = RenderOptions {
        emit_types: true,
        emit_calls: true,
        emit_call_specs: false,
        emit_tx_ext: false,
        flatten: false,
        use_aliases: true,
        emit_reexports: false,
        external_types: BTreeMap::new(),
    };

    for (external_package, (_, _, external)) in packages {
        if external_package == package {
            continue;
        }
        opts.add_external_package(
            external,
            format!("crate::move_bindings::{external_package}"),
        );
    }

    render_package_parts(normalized, &opts)
}

fn write_move_binding_package_files(
    package: &str,
    generated: sui_move_codegen::render::RenderedPackageParts,
    out_dir: &Path,
) {
    let mut package_out =
        String::from("// @generated by build.rs from src/move_bindings/ir JSON; do not edit.\n");
    package_out.push_str(&generated.root);

    for (module, body) in generated.modules {
        let module_file = format!("{package}_{module}_types.rs");
        package_out.push_str(&format!(
            "include!(concat!(env!(\"OUT_DIR\"), \"/{module_file}\"));\n"
        ));

        let mut module_out = String::from(
            "// @generated by build.rs from src/move_bindings/ir JSON; do not edit.\n",
        );
        module_out.push_str(&body);
        let out_path = out_dir.join(&module_file);
        fs::write(&out_path, module_out)
            .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_path.display()));
    }

    let out_path = out_dir.join(format!("{package}_types.rs"));
    fs::write(&out_path, package_out)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_path.display()));
}
