//! Scaffolds new Rust and Move Tool projects from the bundled templates.

use {
    crate::{command_title, display::json_output, loading, notify_success, prelude::*},
    convert_case::{Boundary, Case, Casing},
    minijinja::{context, Environment},
    tokio::fs::create_dir_all,
};

/// Available templates for tool generation.
#[derive(Clone, Debug, ValueEnum)]
pub(crate) enum ToolTemplate {
    Rust,
    Move,
}

/// The `execute` signature generated by the Move template. It mirrors
/// `nexus_sdk::types::OnchainToolMode`, which cannot implement clap's
/// `ValueEnum` because the SDK does not depend on clap.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, ValueEnum)]
pub(crate) enum MoveToolMode {
    /// The `execute` parameters begin with `UIDRequirements` and
    /// `OnchainToolResult`.
    #[default]
    Standard,
    /// The `execute` parameters begin with an Agent vertex authorization
    /// proof; every DAG vertex over the Tool needs an authorization binding.
    WorkflowAuthorization,
}

/// Converts a Tool name to `case`, keeping digits attached to the surrounding
/// letters: `sha256_hash` stays `sha256_hash`, `base64Encode` becomes
/// `base64_encode`.
fn convert_name(name: &str, case: Case) -> String {
    name.without_boundaries(&[
        Boundary::LOWER_DIGIT,
        Boundary::UPPER_DIGIT,
        Boundary::DIGIT_LOWER,
    ])
    .to_case(case)
}

impl ToolTemplate {
    /// For each template, transform the template based on the given variables
    /// and return the files to write.
    pub(crate) fn transform(
        &self,
        name: &str,
        description: &str,
        mode: MoveToolMode,
    ) -> AnyResult<Vec<(String, Option<String>)>> {
        let description = description.trim();
        if description.is_empty() {
            anyhow::bail!("Tool description must not be empty");
        }

        let files = match self {
            ToolTemplate::Rust => {
                let name_kebab_case = convert_name(name, Case::Kebab);
                let name_pascal_case = convert_name(name, Case::Pascal);
                let description_literal = serde_json::to_string(description)?;

                let mut env = Environment::new();

                env.add_template("main", include_str!("templates/rust/main.rs.jinja"))?;
                env.add_template("cargo", include_str!("templates/rust/Cargo.toml.jinja"))?;

                let main_template = env.get_template("main")?;
                let cargo_template = env.get_template("cargo")?;

                vec![
                    ("src".to_string(), None),
                    (
                        "src/main.rs".to_string(),
                        Some(main_template.render(
                            context! { name_kebab_case, name_pascal_case, description_literal },
                        )?),
                    ),
                    (
                        "Cargo.toml".to_string(),
                        Some(
                            cargo_template
                                .render(context! { name_kebab_case, name_pascal_case })?,
                        ),
                    ),
                ]
            }
            ToolTemplate::Move => {
                let name_snake_case = convert_name(name, Case::Snake);
                let name_pascal_case = convert_name(name, Case::Pascal);
                let name_uppercase = convert_name(name, Case::UpperSnake);
                let workflow_authorization = matches!(mode, MoveToolMode::WorkflowAuthorization);
                let description_doc = description
                    .lines()
                    .map(|line| format!("//! {}", line.trim()))
                    .collect::<Vec<_>>()
                    .join("\n");

                let mut env = Environment::new();
                env.set_trim_blocks(true);
                env.set_lstrip_blocks(true);

                env.add_template("move_toml", include_str!("templates/move/Move.toml.jinja"))?;
                env.add_template("tool_move", include_str!("templates/move/tool.move.jinja"))?;
                env.add_template(
                    "tests_move",
                    include_str!("templates/move/tests.move.jinja"),
                )?;
                env.add_template("gitignore", include_str!("templates/move/.gitignore.jinja"))?;

                let move_toml_template = env.get_template("move_toml")?;
                let tool_move_template = env.get_template("tool_move")?;
                let tests_move_template = env.get_template("tests_move")?;
                let gitignore_template = env.get_template("gitignore")?;

                vec![
                    ("sources".to_string(), None),
                    ("tests".to_string(), None),
                    (
                        "Move.toml".to_string(),
                        Some(move_toml_template.render(context! { name_snake_case })?),
                    ),
                    (
                        format!("sources/{name_snake_case}.move"),
                        Some(tool_move_template.render(context! {
                            name_snake_case,
                            name_pascal_case,
                            name_uppercase,
                            description_doc,
                            workflow_authorization,
                        })?),
                    ),
                    (
                        format!("tests/{name_snake_case}_tests.move"),
                        Some(tests_move_template.render(context! { name_snake_case })?),
                    ),
                    (
                        ".gitignore".to_string(),
                        Some(gitignore_template.render(context! {})?),
                    ),
                ]
            }
        };

        Ok(files
            .into_iter()
            .map(|(path, content)| {
                (
                    path,
                    content.map(|text| format!("{}\n", text.trim_end_matches('\n'))),
                )
            })
            .collect())
    }
}

/// Create a new tool based on the provided name and template.
pub(crate) async fn create_new_tool(
    name: String,
    description: String,
    template: ToolTemplate,
    mode: Option<MoveToolMode>,
    target: PathBuf,
) -> AnyResult<(), NexusCliError> {
    if mode.is_some() && !matches!(template, ToolTemplate::Move) {
        return Err(NexusCliError::Any(anyhow::anyhow!(
            "--mode only applies to the move template"
        )));
    }

    command_title!(
        "Creating a new Nexus Tool '{name}' with template '{template:?}' in '{target}'",
        target = target.display()
    );

    let transforming_template = loading!("Transforming template...");

    let files = match template.transform(&name, &description, mode.unwrap_or_default()) {
        Ok(files) => files,
        Err(e) => {
            transforming_template.error();

            return Err(NexusCliError::Any(e));
        }
    };

    transforming_template.success();

    // Write each file that was generated by the template.
    let writing_file = loading!("Writing template files...");

    // Create the tool's root directory.
    let root_directory = target.join(&name);

    if let Err(e) = create_dir_all(&root_directory).await {
        writing_file.error();

        return Err(NexusCliError::Io(e));
    };

    for (path, content) in files {
        let path = target.join(&name).join(&path);

        // Check if we need to create a directory.
        let content = match content {
            Some(content) => content,
            None => {
                if let Err(e) = create_dir_all(path).await {
                    writing_file.error();

                    return Err(NexusCliError::Io(e));
                }

                continue;
            }
        };

        // `tokio::fs::write` flushes and closes the file before returning; a
        // dropped `tokio::fs::File` does not flush its buffer, which can leave a
        // scaffolded file empty for a reader racing the drop.
        if let Err(e) = tokio::fs::write(path, content.as_bytes()).await {
            writing_file.error();

            return Err(NexusCliError::Io(e));
        }
    }

    writing_file.success();
    notify_success!("Created Tool scaffold at {}", root_directory.display());

    json_output(&json!({
        "path": root_directory,
    }))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use {super::*, assert_matches::assert_matches};

    async fn assert_ends_with_one_newline(path: &std::path::Path) {
        let contents = tokio::fs::read_to_string(path).await.unwrap();

        assert!(
            contents.ends_with('\n') && !contents.ends_with("\n\n"),
            "{} must end with exactly one newline",
            path.display()
        );
    }

    fn move_source(name: &str, mode: MoveToolMode) -> String {
        let source_path = format!("sources/{}.move", convert_name(name, Case::Snake));

        ToolTemplate::Move
            .transform(name, "Increments an onchain counter.", mode)
            .unwrap()
            .into_iter()
            .find_map(|(path, contents)| (path == source_path).then_some(contents))
            .flatten()
            .expect("Move source present")
    }

    fn rust_manifest(name: &str) -> String {
        ToolTemplate::Rust
            .transform(name, "Echoes its input.", MoveToolMode::Standard)
            .unwrap()
            .into_iter()
            .find_map(|(path, contents)| (path == "Cargo.toml").then_some(contents))
            .flatten()
            .expect("Cargo.toml present")
    }

    #[tokio::test]
    async fn test_create_new_tool() {
        let tempdir = tempfile::tempdir().unwrap().keep();

        let result = create_new_tool(
            "test".to_string(),
            "Returns a quoted \"test\" result.".to_string(),
            ToolTemplate::Rust,
            None,
            tempdir.clone(),
        )
        .await;

        assert_matches!(result, Ok(()));

        // Check that main file was written with the correct contents.
        let path = tempdir.join("test/src/main.rs");
        let contents = tokio::fs::read_to_string(path).await.unwrap();

        assert!(contents.contains("enum Output {\n    Ok {\n        // Add output ports for the `Ok` variant\n    },\n    Err {\n        reason: String,\n        code: Option<u16>\n    },\n}"));
        assert!(contents.contains("    async fn new() -> Self {\n        Self\n    }"));
        assert!(contents.contains("    fn fqn() -> ToolFqn {\n        // The fully qualified name of the tool.\n\n        fqn!(\"domain.author.test@1\")\n    }"));
        assert!(contents.contains("    fn path() -> &'static str {\n        \"\"\n    }"));
        assert!(contents.contains(
            "    fn description() -> &'static str {\n        \"Returns a quoted \\\"test\\\" result.\"\n    }"
        ));
        assert!(contents.contains("struct Test;"));
        assert!(contents.contains("impl NexusTool for Test {"));

        // Check that manifest file was written with the correct contents.
        let path = tempdir.join("test/Cargo.toml");
        let contents = tokio::fs::read_to_string(path).await.unwrap();

        assert!(contents.contains(r#"name = "test""#));
        let version = env!("CARGO_PKG_VERSION");
        assert!(contents.contains(&format!(r#"nexus-sdk = "{version}""#)));
        assert!(contents.contains(&format!(r#"nexus-toolkit = "{version}""#)));
        assert!(!contents.contains("git ="));

        for file in ["test/src/main.rs", "test/Cargo.toml"] {
            assert_ends_with_one_newline(&tempdir.join(file)).await;
        }
    }

    #[tokio::test]
    async fn test_create_new_move_tool() {
        let tempdir = tempfile::tempdir().unwrap().keep();

        let result = create_new_tool(
            "test_tool".to_string(),
            "Increments an onchain counter.".to_string(),
            ToolTemplate::Move,
            None,
            tempdir.clone(),
        )
        .await;

        assert_matches!(result, Ok(()));

        // Check that directories were created.
        let sources_dir = tempdir.join("test_tool/sources");
        assert!(sources_dir.exists());

        let tests_dir = tempdir.join("test_tool/tests");
        assert!(tests_dir.exists());

        // Check that Move.toml was written with correct contents.
        let move_toml_path = tempdir.join("test_tool/Move.toml");
        let move_toml_contents = tokio::fs::read_to_string(move_toml_path).await.unwrap();

        assert!(move_toml_contents.contains(r#"name = "test_tool""#));
        assert!(move_toml_contents.contains(r#"version = "1.0.0""#));
        assert!(move_toml_contents.contains("edition = \"2024\""));
        assert!(move_toml_contents
            .contains(r#"nexus_primitives = { r.mvr = "@talus/nexus-primitives" }"#));
        assert!(move_toml_contents
            .contains(r#"nexus_interface = { r.mvr = "@talus/nexus-interface" }"#));
        assert!(
            !move_toml_contents.contains("local ="),
            "scaffolded Move.toml must not point at local Nexus package paths"
        );
        assert!(
            !move_toml_contents.contains("[addresses]"),
            "scaffolded Move.toml must not declare [addresses] (old-style marker)"
        );

        // Check that the main Move file was written with correct contents.
        let move_file_path = tempdir.join("test_tool/sources/test_tool.move");
        let move_contents = tokio::fs::read_to_string(move_file_path).await.unwrap();

        assert!(move_contents.starts_with("//! Increments an onchain counter.\n"));
        assert!(move_contents.contains("module test_tool::test_tool;"));
        assert!(move_contents.contains("public struct TEST_TOOL has drop {}"));
        assert!(move_contents.contains("public struct TestToolWitness has key, store"));
        assert!(move_contents.contains("public struct TestToolState has key"));
        assert!(move_contents.contains("witness: Bag"));
        assert!(move_contents.contains("public enum Output"));
        assert!(move_contents.contains("fun init(_otw: TEST_TOOL, ctx: &mut TxContext)"));
        assert!(move_contents.contains("public fun execute("));
        assert!(!move_contents.contains("entry fun execute("));
        assert!(move_contents.contains(
            "public fun execute(\n    requirements: UIDRequirements,\n    result: OnchainToolResult,\n"
        ));
        assert!(move_contents.contains("/// 1. Internal workflow requirements parameter"));
        assert!(move_contents.contains("/// 6. Must be public"));
        assert!(!move_contents.contains("AgentVertexAuthorization"));
        assert!(!move_contents.contains("primitive_authorization"));
        assert!(
            !move_contents.contains("\n\n\n"),
            "mode conditionals must not leave blank lines"
        );
        assert!(move_contents.contains("requirements: UIDRequirements"));
        assert!(move_contents.contains("result: OnchainToolResult"));
        assert!(move_contents.contains("requirements.satisfy(&state.witness().id"));
        assert!(move_contents.contains(
            "onchain_tool_result::finalize_and_share(result, requirements, output, ctx);"
        ));
        assert!(move_contents.contains("public fun tool_witness_id(self: &TestToolState): ID"));
        assert!(
            move_contents.contains("public fun init_for_test(otw: TEST_TOOL, ctx: &mut TxContext)")
        );

        // Check that the test file was written.
        let test_file_path = tempdir.join("test_tool/tests/test_tool_tests.move");
        let test_contents = tokio::fs::read_to_string(test_file_path).await.unwrap();

        assert!(test_contents.contains("module test_tool::test_tool_tests;"));
        assert!(test_contents.contains("fun test_test_tool()"));

        // Check that .gitignore was written.
        let gitignore_path = tempdir.join("test_tool/.gitignore");
        let gitignore_contents = tokio::fs::read_to_string(gitignore_path).await.unwrap();

        assert!(gitignore_contents.contains("build/*"));

        for file in [
            "test_tool/Move.toml",
            "test_tool/sources/test_tool.move",
            "test_tool/tests/test_tool_tests.move",
            "test_tool/.gitignore",
        ] {
            assert_ends_with_one_newline(&tempdir.join(file)).await;
        }
    }

    #[test]
    fn workflow_authorization_mode_adds_the_authorization_proof() {
        let move_contents = move_source("test_tool", MoveToolMode::WorkflowAuthorization);

        assert!(
            move_contents.contains("use nexus_interface::authorization::AgentVertexAuthorization;")
        );
        assert!(move_contents.contains(
            "use nexus_primitives::authorization::{Self as primitive_authorization, ProvenValue};"
        ));
        assert!(move_contents.contains(
            "public fun execute(\n    authorization: ProvenValue<AgentVertexAuthorization>,\n    requirements: UIDRequirements,\n"
        ));
        assert!(move_contents.contains("    primitive_authorization::drop(authorization);\n"));
        assert!(move_contents.contains("/// 1. Internal authorization parameter"));
        assert!(move_contents.contains("/// 2. Internal workflow requirements parameter"));
        assert!(move_contents.contains("/// 7. Must be public"));
        assert!(move_contents.contains("--authorization-binding"));
        assert!(
            !move_contents.contains("\n\n\n"),
            "mode conditionals must not leave blank lines"
        );
    }

    #[test]
    fn digits_stay_attached_to_tool_names() {
        let move_contents = move_source("sha256_hash", MoveToolMode::Standard);

        assert!(move_contents.contains("module sha256_hash::sha256_hash;"));
        assert!(move_contents.contains("public struct SHA256_HASH has drop {}"));
        assert!(move_contents.contains("public struct Sha256HashWitness has key, store"));

        assert!(rust_manifest("sha256-hash").contains(r#"name = "sha256-hash""#));
    }

    #[test]
    fn digit_before_uppercase_still_splits_words() {
        let move_contents = move_source("base64Encode", MoveToolMode::Standard);

        assert!(move_contents.contains("module base64_encode::base64_encode;"));
        assert!(move_contents.contains("public struct BASE64_ENCODE has drop {}"));
        assert!(move_contents.contains("public struct Base64EncodeWitness has key, store"));

        assert!(rust_manifest("base64Encode").contains(r#"name = "base64-encode""#));
    }

    #[tokio::test]
    async fn mode_is_rejected_for_the_rust_template() {
        let tempdir = tempfile::tempdir().unwrap().keep();

        let error = create_new_tool(
            "test".to_string(),
            "Echoes its input.".to_string(),
            ToolTemplate::Rust,
            Some(MoveToolMode::Standard),
            tempdir.clone(),
        )
        .await
        .expect_err("--mode must be rejected outside the move template");

        assert_eq!(
            error.to_string(),
            "--mode only applies to the move template"
        );
        assert!(
            !tempdir.join("test").exists(),
            "nothing is written when the flag combination is rejected"
        );
    }

    #[test]
    fn blank_description_is_rejected_before_scaffolding() {
        let error = ToolTemplate::Rust
            .transform("test", " \n\t", MoveToolMode::Standard)
            .expect_err("blank descriptions must be rejected");

        assert_eq!(error.to_string(), "Tool description must not be empty");
    }
}
