name: Update Coverage Baseline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    uses: ./.github/workflows/detect_rust_changes.yml

  update-baseline:
    runs-on: ubuntu-latest
    name: Update Coverage Baseline
    needs: detect-changes
    if: ${{ !cancelled() && (github.event_name == 'workflow_dispatch' || needs.detect-changes.outputs.changed != 'false') }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Coverage
        uses: ./.github/actions/coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          codecov-flags: unittests,baseline
          codecov-name: main-baseline
          cache-key-suffix: -main-baseline
