name: Update Coverage Baseline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-baseline:
    runs-on: ubuntu-latest
    name: Update Coverage Baseline
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Coverage
        uses: ./.github/actions/coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          codecov-flags: unittests,baseline
          codecov-name: main-baseline
          cache-key-suffix: -main-baseline
