# GitHub workflow to run the pre-commit hook.

name: Pre-commit hook
on:
  pull_request:
  push:
    branches:
      - main

# Fix for OOM.
env:
  RUST_CACHE_VERBOSE: true
  CARGO_BUILD_JOBS: 1
  CARGO_INCREMENTAL: 1
  RUSTFLAGS: >
    -C codegen-units=1

jobs:
  detect-changes:
    uses: ./.github/workflows/detect_changes.yml
    with:
      files: |
        **/**

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Set up Docker for tests
      - name: Set up Docker for tests
        uses: docker/setup-docker-action@v4

      # Install Rust
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
        with:
          toolchain: stable, nightly-2025-01-06
          override: true
          components: rustfmt, clippy
#          cache-directories: ~/.npm

#      # Install Rust cache
#      - name: Rust cache
#        uses: Swatinem/rust-cache@v2
#        with:
#          cache-targets: true
#          cache-on-failure: true
#          cache-all-crates: true

      # Extra cache for anything that is not cached by rust-cache
      - name: Extra cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('helpers/npm-install-g.txt') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Install Rust tools
      # For more tools, see: https://github.com/taiki-e/install-action/blob/main/TOOLS.md
      - name: Install Rust tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,just,cargo-nextest,typos

      # Install NPM stuff (markdownlint-cli2)
      - name: Install NPM stuff (markdownlint-cli2)
        run: |
          command -v markdownlint-cli2 || \
          while read -r tool; do
            npm install -g "$tool"
          done < helpers/npm-install-g.txt

      - run: cargo +stable --version && cargo +nightly-2025-01-06 --version
      - run: ./.pre-commit/pre-commit
